
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./backend/media:/usr/share/nginx/html/media  # Монтирование медиа файлов для фронта

networks:
  default:
    driver: bridge 